version: "3.8"

services:
  dev:
    build:
      context: .
      args:
        #Replace with results of $(id -u) and $(id -g) if necessary
        UID: %UID%
        GRP: %GID%
    container_name: nvim-node
    restart: always
    volumes:
      - ./app:/app:z
      - node_modules:/app/node_modules/
      - dotlocal:/home/app/.local
      - ~/.config/nvim:/home/app/.config/nvim:z
      - ~/.gitconfig:/home/app/.gitconfig:ro
      - ~/.ssh/github_id_ed25519:/home/app/.ssh/github_id_ed25519:z
      - /etc/localtime:/etc/localtime:ro
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY:z
    stdin_open: true
    tty: true
    ports:
      - "22:22"
    user: %UID%:%GID% #Replace with results of $(id -u) and $(id -g) if necessary
    environment:
      XDG_RUNTIME_DIR: /tmp
      TERM: xterm-256color
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_DATA_DIRS: /tmp/XDG_DATA_DIRS
      ZDOTDIR:
        /home/app/.config/zsh
        #    security_opt:  #This this if copying to system clipboard fails.  Needed with moby engine but not Docker proper.
        #      - label:type:container_runtime_t
volumes:
  dotlocal:
  node_modules:
